---
# Playbook to deploy Moonshot Application
- name: Deploy Moonshot Application on Kubernetes
  hosts: nodes
  become: true # Ensures root privileges where needed
  roles:
    - docker
    # Step 1: Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Step 2: Install required dependencies
    - name: Install required dependencies
      apt:
        name:
          - python3-pip
          - libpq-dev
          - build-essential
          - python3-dev
          - curl
        state: present

    # Step 3: Install Python dependencies globally
    - name: Install Python dependencies from requirements.txt
      pip:
        requirements: /app/requirements.txt

    # Step 4: Create application directory
    - name: Create application directory
      file:
        path: /app
        state: directory
        owner: root
        group: root
        mode: "0755"

    # Step 5: Copy requirements.txt
    - name: Copy requirements.txt to the node
      copy:
        src: docker/moonshot/requirements.txt
        dest: /app/requirements.txt

    # Step 6: Copy application code
    - name: Copy Moonshot application code
      copy:
        src: docker/moonshot/
        dest: /app/
        owner: root
        group: root
        mode: "0755"

    # Step 7: Ensure the script is executable
    - name: Set execution permissions for moonshotscript.sh
      file:
        path: /app/moonshotscript.sh
        mode: "0755"

    # Step 8: Run the Moonshot application script
    - name: Run the application
      command: "/app/moonshotscript.sh"
