---
# Playbook to deploy Moonshot and its components
- name: Deploy Moonshot Application
  hosts: all
  become: true # Run tasks as root

  vars:
    docker_image_name: moonshot_image
    docker_container_name: moonshot_container
    app_port: 8000

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker.io
        state: present

    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Copy application files to the target machine
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../docker"
        dest: /tmp/moonshot
        remote_src: no

    - name: Build Docker image
      ansible.builtin.command:
        cmd: docker build -t "{{ docker_image_name }}" .
        chdir: /tmp/moonshot

    - name: Stop existing container if running
      ansible.builtin.command:
        cmd: docker stop "{{ docker_container_name }}"
      ignore_errors: true

    - name: Remove existing container if exists
      ansible.builtin.command:
        cmd: docker rm "{{ docker_container_name }}"
      ignore_errors: true

    - name: Run Docker container
      ansible.builtin.command:
        cmd: >
          docker run -d --name "{{ docker_container_name }}"
          -p "{{ app_port }}:8000"
          "{{ docker_image_name }}"
