---
# Playbook to deploy Moonshot Application
- name: Deploy Moonshot Application on Kubernetes
  hosts: nodes
  become: true # Ensures root privileges where needed
  roles:
    - docker
    tags: ["docker"]

    - docker-moon
    tags: ["moonshot"]

  vars:
    build: true # Set build to true here
