---
# Playbook to deploy Moonshot Application
- name: Deploy Moonshot Application on Kubernetes
  hosts: nodes
  become: true # Ensures root privileges where needed
  roles:
    - role: docker
      tags: ["docker"]

    - role: docker-moon
      tags: ["moonshot"]

    - role: docker-postgres
      tags: ["postgres"]

    - role: k8s-moon
      tags: ["moonshot-deploy"]

  vars:
    build: true # Set build to true here
